Resources:
  AutoCreateCodeBuild:
    Type: AWS::Events::Rule
    Properties:
      Description: Auto create codeBuild
      EventPattern:
        source:
          - "aws.codecommit"
        detail-type:
          - "CodeCommit Pull Request State Change"
        detail:
          event:
            - "pullRequestCreated"
          pullRequestStatus:
            - "Open"
      Name: AutoCreateCodeBuild
      State: "ENABLED"
      Targets:
        - Arn: arn:aws:lambda:ap-northeast-1:${self:provider.environment.ACCOUNT}:function:autoCreateCodeBuild-dev
          Id: autoCreateCodeBuild
  AutoStartCodeBuild:
    Type: AWS::Events::Rule
    Properties:
      Description: Auto start codeBuild
      EventPattern:
        source:
          - "aws.codecommit"
        detail-type:
          - "CodeCommit Pull Request State Change"
        detail:
          event:
            - "pullRequestSourceBranchUpdated"
          pullRequestStatus:
            - "Open"
      Name: AutoStartCodeBuild
      State: "ENABLED"
      Targets:
        - Arn: arn:aws:lambda:ap-northeast-1:${self:provider.environment.ACCOUNT}:function:autoStartCodeBuild-dev
          Id: autoStartCodeBuild
  AutoDeleteCodeBuild:
    Type: AWS::Events::Rule
    Properties:
      Description: Auto delete codeBuild
      EventPattern:
        source:
          - "aws.codecommit"
        detail-type:
          - "CodeCommit Pull Request State Change"
        detail:
          event:
            - "pullRequestStatusChanged"
            - "pullRequestMergeStatusUpdated"
          pullRequestStatus:
            - "Closed"
      Name: AutoDeleteCodeBuild
      State: "ENABLED"
      Targets:
        - Arn: arn:aws:lambda:ap-northeast-1:${self:provider.environment.ACCOUNT}:function:autoDeleteCodeBuild-dev
          Id: autoDeleteCodeBuild
  AutoCreateCodeBuildLambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: "autoCreateCodeBuild-${self:provider.stage}"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        "Fn::GetAtt": [AutoCreateCodeBuild, Arn]
    DependsOn: AutoCreateCodeBuild
  AutoStartCodeBuildLambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: "autoStartCodeBuild-${self:provider.stage}"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        "Fn::GetAtt": [AutoStartCodeBuild, Arn]
    DependsOn: AutoStartCodeBuild
  AutoDeleteCodeBuildLambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: "autoDeleteCodeBuild-${self:provider.stage}"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        "Fn::GetAtt": [AutoDeleteCodeBuild, Arn]
    DependsOn: AutoDeleteCodeBuild
