Resources:
  SlsTestWebAppFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        Name: sls-test-web-app-cache-policy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: false
          EnableAcceptEncodingBrotli: false
          HeadersConfig: #TODO: Heagderは後々精査する
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
  SlsTestWebAppFrontOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig: #TODO: Heagderは後々精査する
          HeaderBehavior: none
        Name: sls-test-web-app-ui-origin-request-policy
        QueryStringsConfig:
          QueryStringBehavior: none
    DependsOn: SlsTestWebAppFrontCachePolicy
  SlsTestWebAppOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI of SlsTestWebApp.
    DependsOn: SlsTestWebAppFrontOriginRequestPolicy
  SlsTestWebAppApiCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        Name: sls-test-web-app-api-cache-policy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: false
          EnableAcceptEncodingBrotli: false
          HeadersConfig: #TODO: Heagderは後々精査する
            HeaderBehavior: none
          QueryStringsConfig: #TODO: QueryStringBehavior: allで失敗する原因を調査する
            QueryStringBehavior: none
    DependsOn: SlsTestWebAppOai
  SlsTestWebAppApiOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig: #TODO: Heagderは後々精査する
          HeaderBehavior: none
        Name: sls-test-web-app-api-origin-request-policy
        QueryStringsConfig: #TODO: QueryStringBehavior: allで失敗する原因を調査する
          QueryStringBehavior: none
    DependsOn: SlsTestWebAppApiCachePolicy
  SlsTestWebAppFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: SlsTestWebAppUi
            DomainName: sls-test-web-app-front-dev.s3.ap-northeast-1.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity:
                "Fn::Join":
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: SlsTestWebAppOai
          - Id: SlsTestWebAppApi
            DomainName: ${cf.${self:provider.environment.API_GATEWAY_REGION}:slsTestApp-${self:provider.stage}.Id}.execute-api.${self:provider.environment.API_GATEWAY_REGION}.amazonaws.com
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: https-only
              OriginKeepaliveTimeout: 30
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - TLSv1.2
        Comment: Distribution of SlsTestWebApp Client and API.
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId:
            Ref: SlsTestWebAppFrontCachePolicy
          Compress: false
          OriginRequestPolicyId:
            Ref: SlsTestWebAppFrontOriginRequestPolicy
          TargetOriginId: SlsTestWebAppUi
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId:
              Ref: SlsTestWebAppApiCachePolicy
            Compress: false
            OriginRequestPolicyId:
              Ref: SlsTestWebAppApiOriginRequestPolicy
            PathPattern: /dev/slsTestApp/*
            TargetOriginId: SlsTestWebAppApi
            ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Logging:
          Bucket: front-log-dev.s3.ap-northeast-1.amazonaws.com
          IncludeCookies: false
          Prefix: cloudfront
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        WebACLId: ${cf:slsTestWebAppWaf-${self:provider.stage}.Arn}
